### PR TITLE
Readme update

### PR DESCRIPTION
**Pull request by TomChen7**
Added myself to Readme

### CODE REVIEW

**Review by hyunwoo312 — CHANGES_REQUESTED** [review]
I think you don't have the latest change from mainline. Can you `git pull` the mainline changes then make the README change again?

**Comment by TomChen7** [comment]
it says already up to date?

**Comment by TomChen7** [comment]
ill do setup tmr i got a 8:30 to wake up 4

**Comment by hyunwoo312** [comment]
Sorry, I did not see the comments. I will need to set up the github hook so that it shows replies in discord...

and also mb, it looks right. Merging

**Review by hyunwoo312 — APPROVED** [review]

**Pull request merged**
